task:
  name: LinuxGlibcAarch64
  only_if: $CIRRUS_BRANCH == 'master'
  only_if: $CIRRUS_RELEASE != ''
  env:
    GITHUB_TOKEN: ENCRYPTED[c55719815e6b9431df4596dc746645ece3acbd2917ffa29c71a1636d232aa77b7a3684b31667de46f028ca594d7a4b20]
    CARGO_TERM_COLOR: always
  arm_container:
    image: fedora:latest
  prepare_script:
    - whoami
    - dnf check-update -q && dnf up -q -y
    - dnf group install -y "C Development Tools and Libraries" "Development Tools"
    - dnf in -y curl openssl-devel
    - curl https://sh.rustup.rs -sSf | bash -s -- -y
    - . $HOME/.cargo/env
    - cargo install cargo-auditable cargo-audit
  build_script:
    - whoami
    - . $HOME/.cargo/env
    - ls -lah
    - rustc --version
    - cargo auditable build --release --locked
  hash_script:
    - whoami
    - ls -lah
    - cd target/release
    - mv hctl hctl-linux-glibc-aarch64
    - sha256sum hctl-linux-glibc-aarch64 > sha256-hctl-linux-glibc-aarch64
    - mv hctl-linux-glibc-aarch64 ../../ && mv sha256-hctl-linux-glibc-aarch64 ../../
  upload_script:
    - whoami
    - ls -lah
    - files_to_upload=($(ls | grep hctl)); . ./upload.sh
      
task:
  name: LinuxMuslAarch64
  only_if: $CIRRUS_BRANCH == 'master'
  only_if: $CIRRUS_RELEASE != ''
  env:
    GITHUB_TOKEN: ENCRYPTED[c55719815e6b9431df4596dc746645ece3acbd2917ffa29c71a1636d232aa77b7a3684b31667de46f028ca594d7a4b20]
    CARGO_TERM_COLOR: always
  arm_container:
    image: alpine:latest
  prepare_script:
    - apk -U upgrade
    - apk add curl make pkgconf bash build-base openssl openssl-dev openssl-libs-static rust cargo
    - cargo install cargo-auditable cargo-audit
  build_script:
    - whoami
    - ls -lah
    - rustc --version
    - export PATH="$PATH:$HOME/.cargo/bin"
    - cargo auditable build --release --locked
  hash_script:
    - whoami
    - cd target/release
    - mv hctl hctl-linux-musl-aarch64
    - sha256sum hctl-linux-musl-aarch64 > sha256-hctl-linux-musl-aarch64
    - mv hctl-linux-musl-aarch64 ../../ && mv sha256-hctl-linux-musl-aarch64 ../../
  upload_script:
    - whoami
    - ls -lah
    - files_to_upload=($(ls | grep hctl)); . ./upload.sh
    
task:
  name: MacosxSilicon
  only_if: $CIRRUS_BRANCH == 'master'
  only_if: $CIRRUS_RELEASE != ''
  env:
    GITHUB_TOKEN: ENCRYPTED[c55719815e6b9431df4596dc746645ece3acbd2917ffa29c71a1636d232aa77b7a3684b31667de46f028ca594d7a4b20]
    CARGO_TERM_COLOR: always
  macos_instance:
    image: ghcr.io/cirruslabs/macos-sonoma-base:latest
  prepare_script:
    - whoami
    - NONINTERACTIVE=1 brew update
    - NONINTERACTIVE=1 brew outdated
    - NONINTERACTIVE=1 brew upgrade
    - NONINTERACTIVE=1 brew install pkg-config make curl coreutils openssl@3
    - curl https://sh.rustup.rs -sSf | bash -s -- -y
    - . $HOME/.cargo/env
    - cargo install cargo-auditable cargo-audit
  build_script:
    - whoami
    - . $HOME/.cargo/env
    - ls -lah
    - rustc --version
    - cargo auditable build --release --locked
  hash_script:
    - whoami
    - cd target/release
    - mv hctl hctl-macosx-silicon
    - sha256sum hctl-macosx-silicon > sha256-hctl-macosx-silicon
    - mv hctl-macosx-silicon ../../ && mv sha256-hctl-macosx-silicon ../../
  upload_script:
    - whoami
    - ls -lah
    - files_to_upload=($(ls | grep hctl)); . ./upload.sh

task:
  name: LinuxMuslAarch64
  only_if: $CIRRUS_BRANCH == 'dev'
  env:
    GITHUB_TOKEN: ENCRYPTED[c55719815e6b9431df4596dc746645ece3acbd2917ffa29c71a1636d232aa77b7a3684b31667de46f028ca594d7a4b20]
    CARGO_TERM_COLOR: always
  arm_container:
    image: alpine:latest
  prepare_script:
    - apk -U upgrade
    - apk add curl make pkgconf bash build-base openssl openssl-dev openssl-libs-static
    - curl https://sh.rustup.rs -sSf | bash -s -- -y
    - . $HOME/.cargo/env
    - cargo install cargo-auditable cargo-audit
  build_script:
    - whoami
    - . $HOME/.cargo/env
    - ls -lah
    - rustc --version
    - cargo auditable build --release --locked
  hash_script:
    - whoami
    - cd target/release
    - mv hctl hctl-linux-musl-aarch64
    - sha256sum hctl-linux-musl-aarch64 > sha256-hctl-linux-musl-aarch64
    - mv hctl-linux-musl-aarch64 ../../ && mv sha256-hctl-linux-musl-aarch64 ../../