name: Release for NetBSD amd64

on:
  push:
    tags:
      - '*'

jobs:
  test:
    runs-on: macos-12
    name: Release for NetBSD
    steps:
    - uses: actions/checkout@v3
    - name: Build in NetBSD VM
      id: compile
      uses: vmactions/netbsd-vm@v0
      with:
        usesh: false
        mem: 8192        
        prepare: |
          whoami
          export PKG_PATH="http://cdn.netbsd.org/pub/pkgsrc/packages/NetBSD/amd64/.$(uname -r | cut -d '.' -f 1).0_current/All/"
          /usr/sbin/pkg_add -v pkgin
          pkgin update
          pkgin -y upgrade
          pkgin -y install curl pkgconf openssl coreutils p5-Digest-SHA3 mozilla-rootcerts-openssl ca-certificates
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          . $HOME/.cargo/env
        run: |
          whoami
          . $HOME/.cargo/env
          ls -lah
          rustc --version
          cargo build --release
          cd target/release
          mv hctl hctl-netbsd-amd64
          shasum -a 256 hctl-netbsd-amd64 > sha256-hctl-netbsd-amd64
          
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/hctl-netbsd-amd64
        asset_name: hctl-netbsd-amd64
        tag: ${{ github.ref }}
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/sha256-hctl-netbsd-amd64
        asset_name: sha256-hctl-netbsd-amd64
        tag: ${{ github.ref }}