name: Release for Linux musl amd64

on:
  push:
    tags:
      - '*'
      
env:
  CARGO_TERM_COLOR: always

jobs:
  publish_for_linux_musl_amd64:
    name: Release for Linux musl amd64
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
    - uses: actions/checkout@v3
    - name: Compile
      run: |
          whoami
          apk add curl make pkgconf bash build-base openssl openssl-dev openssl-libs-static
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          . $HOME/.cargo/env
          rustc --version
          cargo build --release
          cd target/release
          mv hctl hctl-linux-musl-amd64
          sha256sum hctl-linux-musl-amd64 > sha256-hctl-linux-musl-amd64
          
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/hctl-linux-musl-amd64
        asset_name: hctl-linux-musl-amd64
        tag: ${{ github.ref }}
    - name: Upload checksum to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/sha256-hctl-linux-musl-amd64
        asset_name: sha256-hctl-linux-musl-amd64
        tag: ${{ github.ref }}