name: Find Minimal Supported Rust Version for Release

on:
  push:
    branches:
      - dev
      
env:
  CARGO_TERM_COLOR: always

jobs:
  publish_for_linux_glibc_amd64:
    name: Release for Linux glibc amd64
    runs-on: ubuntu-latest
    container: foresterre/cargo-msrv:latest
    steps:
    - uses: actions/checkout@v4
    - name: Compile
      run: cargo msrv