name: Release for Illumos amd64   
      
on:
  push:
    branches:
      - dev

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    name: Release for Illumos
    steps:
    - uses: actions/checkout@v4
    - name: Build in OmniOS VM
      id: compile
      uses: vmactions/omnios-vm@v1
      with:
        envs: 'CARGO_TERM_COLOR'  
        usesh: false
        mem: 8192        
        prepare: |
          whoami
          pkg update
          pkg upgrade -y
          pkg install openssl curl gnu-coreutils gcc13 pkg-config perl
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          . $HOME/.cargo/env
          cargo install cargo-auditable cargo-audit
        run: |
          whoami
          . $HOME/.cargo/env
          ls -lah
          uname -a
          rustc --version
          cargo auditable build --release --locked
          cd target/release
          mv hctl hctl-illumos-amd64
          shasum -a 256 hctl-illumos-amd64 > sha256-hctl-illumos-amd64