name: Release for DragonflyBSD amd64

on:
  push:
    branches:
      - dev

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    name: Release for DragonflyBSD
    steps:
    - uses: actions/checkout@v4
    - name: Compile
      id: release_dfly
      uses: vmactions/dragonflybsd-vm@v1
      with:
        envs: 'CARGO_TERM_COLOR'
        usesh: false
        mem: 8192
        prepare: |
          whoami
          pkg update
          pkg upgrade -y
          pkg install -y curl rust pkgconf openssl coreutils p5-Digest-SHA
          cargo install cargo-auditable cargo-audit
          rehash

        run: |
          whoami
          rehash
          ls -lah
          rustc --version
          cargo auditable build --release --locked
          cd target/release
          mv hctl hctl-dragonflybsd-amd64
          shasum -a 256 hctl-dragonflybsd-amd64 > sha256-hctl-dragonflybsd-amd64
